hw_project/hw_project/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

hw_project/quotes/urls.py
from django.urls import path, include

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('quotes/', views.main, name="quotes"),
    path('<int:page>', views.main, name="root_paginate"),
    path('users/', include('users.urls')),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('delete/<int:quote_id>/', views.delete_quote, name='delete_quote'),
    path("show_author/<int:author_id>", views.show_author, name="show_author"),
]

hw_project/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView
from .forms import LoginForm
from .views import RegisterView, ResetPasswordView, CustomLogoutView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("login/", LoginView.as_view(template_name='users/login.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", CustomLogoutView.as_view(), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_project/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.fullname
    
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    
    def __str__(self):
        return self.name
    
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw_project/quotes/forms.py
from django import forms
from .models import Author, Quote



class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        
class QuoteForm(forms.ModelForm):
    quote = forms.CharField(widget=forms.Textarea)
    tags = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Separated by commas'}))
    author = forms.ModelChoiceField(queryset=Author.objects.all(), empty_label="Select an author")

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

hw_project/quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag

from .utils import get_mongodb

# Mongo
# def main (request, page=1):
#     db = get_mongodb()
#     quotes = db.quotes.find()
#     per_page = 10
#     paginator = Paginator(list(quotes), per_page)
#     quotes_on_page = paginator.page(page)
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def show_author(request, author_id):
    author = Author.objects.get(pk=author_id)
    return render(request, 'quotes/show_author.html', context={"author": author})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
    else:
        form = AuthorForm()
    
    return render(request, 'quotes/add_author.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote_text = form.cleaned_data['quote']
            author = form.cleaned_data['author']

            tags_input = form.cleaned_data['tags']

            tags_list = [tag.strip() for tag in tags_input.split(',')]
            
            tags = [Tag.objects.get_or_create(name=tag_name)[0] for tag_name in tags_list]

            quote = Quote(quote=quote_text, author=author)
            quote.save()
            for tag in tags:
                quote.tags.add(tag)

            return redirect('quotes:root')

    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})



@login_required
def delete_quote(request, quote_id):
    try:
        quote = Quote.objects.get(id=quote_id)
        quote.delete()
    except Quote.DoesNotExist:
        pass
    return redirect('quotes:root')

hw_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Contribute author</h1>

{% if messages %}
{% for message in messages%}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Add author</button>
  </form>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Contribute quote</h1>

{% if messages %}
{% for message in messages%}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}
  role="alert">
  {{message}}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
  {% csrf_token %}
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.quote.id_for_label }}">Quote:</span>
      {{ form.quote }}
  </div>
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.tags.id_for_label }}">Tags (Separated by commas):</span>
      {{ form.tags }}
  </div>
  <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="{{ form.author.id_for_label }}">Author:</span>
      {{ form.author }}
  </div>
  <button class="btn btn-primary" type="submit">Add quote</button>
</form>
{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   
        {% load static %}
        <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
        <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <form method="post" action="{% url 'users:logout' %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Logout
                        </button>
                    </form>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Contribute author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Contribute quote</a>
                    {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}

                </p>
            </div>
        </div>
    

        {% block content %} {% endblock %}

    </div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row" >
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
            <a href="/show_author/{{quote.author.id}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                    <a class="tag">{{ tag.name }}</a>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'quotes:delete_quote' quote.id %}">
                {% csrf_token %}
                <button class="btn btn-danger" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">Delete</button>

              </form>

            {% endif %}
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}" href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span>
                </a>
            </li>
    </nav>
    </div>
   
</div>

{% endblock %}

hw_project/quotes/templates/quotes/show_author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">

    <h1>{{author.fullname}}</h1>
    <p>Born: <b>{{author.born_date}}</b> {{author.born_location}} </p>
    <p><b>Description:</b></p> 
    <p>{{author.description}}</p>

</div>

{% endblock %}